name: Deploy WASM

defaults:
  run:
    shell: bash
    working-directory: ./emu-wasm

on:
  push:
    branches: [ master ]
    paths:
      - "emu/**"
      - "emu-wasm/**"
      - "lib/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build WASM
      run: wasm-pack build
    - name: Install dependencies
      run: cd ./www && npm install
    - name: Build web app
      run: cd ./www && npm run build
    - name: Deploy to GH pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www/dist
