name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --release
    - name: Run tests w/ coverage
      run: cargo tarpaulin --release --verbose --workspace --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
